# ===================================================================
# CONFIGURACIÓN GENERAL DE LA APLICACIÓN
# ===================================================================
# Define el nombre identificador del microservicio o aplicación en el contexto de Spring.
spring.application.name=backend

# ===================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS (PostgreSQL)
# ===================================================================
# URL de conexión a la base de datos. 
# Utiliza la variable de entorno 'DB_URL' si existe; de lo contrario, apunta a localhost por defecto.
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-dry-scene-ac4of9fn-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}

# Credenciales de acceso a la base de datos con respaldos (fallbacks) por defecto.
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_vbg3BVm9afyF}

# ===================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===================================================================
# Controla la manipulación automática del esquema de la base de datos.
# 'none' es el valor estándar para producción, ya que evita que Hibernate altere o borre tablas existentes.
spring.jpa.hibernate.ddl-auto=none

# Habilita la impresión de las consultas SQL generadas por Hibernate en la consola.
spring.jpa.show-sql=true

# Da formato estético (con saltos de línea y sangrías) al SQL impreso en consola para facilitar la depuración.
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# CONFIGURACIÓN DE CLOUDINARY
# ===================================================================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dhnnfwmqt}
cloudinary.api-key=${CLOUDINARY_API_KEY:195136858522725}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:Fk7fhyv2L7h1GXFLeUxoSN4BTrQ}